db:
  image: mongo
  ports:
    - 27017
web:
  build: .
  command: npm start
  volumes:
    - ./files:/myapp/files
  ports:
    - 2000:2000
  links:
    - db
  environment:
    # PORT: 3000
    DATABASE_URL: 'mongodb://db/arxivum-dev'
    NODE_ENV: 'prod'

